### ISSUE TITLE
Kuoleman jälkeen samaan leveliin syntyminen

### ISSUE THREAD

**Issue by ghost** [HalooProductions/qli#12]
Jos kuolee esim. level 3:ssa, tällä hetkellä syntyy level 1:seen. Pitäisi syntyä level 3:seen.

**Comment by ghost** [comment]
Turha muuttuja (gameOverStatus)

**Comment by rikuw** [comment]
Esc vois tulla main menu esiin myös

**Comment by aspehkonen** [comment]
Turhat muuttujat poistettu, Continue toimii gameovermenussa.
